Add UAT support; build and logging improvements (#237)
* initial commit with new UAT feeder

* add signup script, update README

* saveguarding around signup-uat.sh

* temp thing

* more experiments

* more experiments

* update

* updates

* updates

* updates

* typo

* updates

* update

* debug

* updates

* update

* update

* update

* updates

* silence wget

* make wget less verbose

* updates

* update

* move file

* Update fr24feed

* Update fr24uat-feed

* Update Dockerfile

* reduce logging

* dockerfile improvements

* bugfix

* updates to readme

* improve logging

* logging improvements

* logging improvements

* make x86 use qemu to ensure latest version is used

* update

* Update fr24feed

* Update fr24uat-feed

* Update fr24feed-log

* Update fr24feed-log

* Update fr24feed-log

* Update fr24feed-log

* updates

* Update fr24uat-feed

* Update Dockerfile

* Update fr24feed-log

* Update fr24feed

* Update fr24feed

* Update fr24uat-feed

* Update fr24feed

* Update fr24uat-feed

* Update fr24uat-feed

* Update fr24uat-feed

* Update fr24feed

* Update install_feeder.sh

* Update install_feeder.sh

* Update install_feeder.sh

* Update install_feeder.sh

* Update install_feeder.sh

* Update get_adsb_key.sh

* Update get_uat_key.sh

* Update install_feeder.sh

* script improvements (#236)

* safeguard against fast loop in fr24feed_check_traffic

output potential errors of tcpdump in fr24feed_check_traffic

* remove redundant things from fr24feed start scripts

* Update fr24feed_check_traffic

* Update fr24feed_check_traffic

---------

Co-authored-by: kx1t <15090643+kx1t@users.noreply.github.com>

* remove separate logging; updated healthscript; other minor changes

* fixing file names

* typos

* updates

---------

Co-authored-by: wiedehopf <wiedehopf@users.noreply.github.com>

diff --git a/rootfs/etc/s6-overlay/scripts/fr24feed_check_traffic b/rootfs/etc/s6-overlay/scripts/fr24feed_check_traffic
--- a/rootfs/etc/s6-overlay/scripts/fr24feed_check_traffic
+++ b/rootfs/etc/s6-overlay/scripts/fr24feed_check_traffic
@@ -3,18 +3,29 @@
 
 # monitor traffic for 5 minutes and write to logfile
 
-# shellcheck disable=SC1091
+# shellcheck disable=SC1091,SC2154
 source /scripts/common
 
 WATCH_INTERVAL="${WATCH_INTERVAL:-300}"
 TRAFFIC_FILE="${TRAFFIC_FILE:-/tmp/packets_rcvd}"
 
 while true; do
-  packets_rcvd="$(sed -z 's/\n/; /g;s/; $//;s/^.*\s\([0-9]\+\) packets captured.*$/\1/g' <<< "$(timeout "$WATCH_INTERVAL" tcpdump -p tcp src port "${BEASTPORT:-30005}" 2>/dev/stdout 1>/dev/null)")"
+  sleep "$WATCH_INTERVAL" &
+
+  if ! pcap_log=$(timeout --preserve-status "$WATCH_INTERVAL" tcpdump -p tcp src port "${BEASTPORT:-30005}" 2>/dev/stdout 1>/dev/null); then
+    "${s6wrap}" echo "[WARNING] Cannot check data flow because tcpdump fails to execute. Try adding NET_ADMIN and NET_RAW capabilities to your container"
+    "${s6wrap}" tail <<< "$pcap_log"
+    packets_rcvd="-1"   
+  else
+    packets_rcvd=$(sed -z 's/\n/; /g;s/; $//;s/^.*\s\([0-9]\+\) packets captured.*$/\1/g' <<< "$pcap_log")
+  fi
+
   echo "$(date +%s) $packets_rcvd" > "${TRAFFIC_FILE}"
   tail -100 "${TRAFFIC_FILE}" > "${TRAFFIC_FILE}".1
   mv -f "${TRAFFIC_FILE}".1 "${TRAFFIC_FILE}"
-  if chk_enabled "$VERBOSE_LOGGING"; then
+  if chk_enabled "$VERBOSE_LOGGING" && [[ "$packets_rcvd" != "-1" ]]; then
     s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args echo "$packets_rcvd packets received from $BEASTHOST in the past 5 minutes"
   fi 
+
+  wait
 done
